### ISSUE TITLE
NullpointerException - getConnection(PlotItem, PlotItem) returns null

### ISSUE THREAD

**Issue by Pureandy** [HanSolo/charts#25]
Hello Gerrit,

In the latest Release is a Bug.

In CirularPlot.java 
line 674: Connection connection = getConnection(item, outgoingItem);
Is trying to get a Connection that should be there but returns null.

line 704: connection.setTooltipText(tooltipText);
Is now trying to set the Tooltip for null.

The Problem is reproducible in the CircularPlotTest class by enabling the currently commented out Outgoings.

    @Override public void init() {
        // Setup Data
        // Wahlberechtigte 61_500_000
        PlotItem australia = new PlotItem("AUSTRALIA", 1_250_000, Color.rgb(255, 51, 51));
        PlotItem india     = new PlotItem("INDIA", 750_000, Color.rgb(255, 153, 51));
        PlotItem china     = new PlotItem("CHINA", 920_000, Color.rgb(255, 255, 51));
        PlotItem japan     = new PlotItem("JAPAN", 1_060_000, Color.rgb(153, 255, 51));
        PlotItem thailand  = new PlotItem("THAILAND", 720_000, Color.rgb(51, 255, 51));
        PlotItem singapore = new PlotItem("SINGAPORE", 800_000, Color.rgb(51, 255, 153));

        // Travel flow
        australia.addToOutgoing(india, 150_000);
        australia.addToOutgoing(china, 90_000);
        australia.addToOutgoing(japan, 180_000);
        australia.addToOutgoing(thailand, 15_000);
        australia.addToOutgoing(singapore, 10_000);

        japan.addToOutgoing(australia, 70_000);

        List<PlotItem> items = List.of(australia, india, china, japan, thailand, singapore );

        // Register listeners to click on connections and items
        items.forEach(item -> {
            item.addItemEventListener(e -> {
                switch (e.getEventType()) {
                    case SELECTED: System.out.println("Selected: " + e.getItem().getName()); break;
                }
            });
        });

        
        india.addToOutgoing(australia, 35_000);
        india.addToOutgoing(china, 10_000);
        india.addToOutgoing(japan, 40_000);
        india.addToOutgoing(thailand, 25_000);
        india.addToOutgoing(singapore, 8_000);

        china.addToOutgoing(australia, 10_000);
        china.addToOutgoing(india, 7_000);
        china.addToOutgoing(japan, 40_000);
        china.addToOutgoing(thailand, 5_000);
        china.addToOutgoing(singapore, 4_000);

        japan.addToOutgoing(australia, 7_000);
        japan.addToOutgoing(india, 8_000);
        japan.addToOutgoing(china, 175_000);
        japan.addToOutgoing(thailand, 11_000);
        japan.addToOutgoing(singapore, 18_000);

        thailand.addToOutgoing(australia, 70_000);
        thailand.addToOutgoing(india, 30_000);
        thailand.addToOutgoing(china, 22_000);
        thailand.addToOutgoing(japan, 120_000);
        thailand.addToOutgoing(singapore, 40_000);

        singapore.addToOutgoing(australia, 60_000);
        singapore.addToOutgoing(india, 90_000);
        singapore.addToOutgoing(china, 110_000);
        singapore.addToOutgoing(japan, 14_000);
        singapore.addToOutgoing(thailand, 30_000);
        

        // Setup Chart
        circluarPlot = CircularPlotBuilder.create()
                                          .prefSize(500, 500)
                                          .items(items)
                                          .connectionOpacity(0.75)
                                          .decimals(0)
                                          .minorTickMarksVisible(false)
                                          .build();

        ConnectionEventListener connectionListener = e -> System.out.println("From: " + e.getConnection().getOutgoingItem().getName() + " -> to: " + e.getConnection().getIncomingItem().getName() + " -> Value: " + e.getConnection().getValue());
        circluarPlot.getConnections().forEach(connection -> connection.addConnectionEventListener(connectionListener));

        if (null != circluarPlot.getConnection(australia, japan)) {
            circluarPlot.getConnection(australia, japan).setFill(Color.BLUE);
            circluarPlot.getConnection(australia, india).setFill(Color.CHOCOLATE);
            circluarPlot.getConnection(japan, australia).setFill(Color.POWDERBLUE);
        }
        circluarPlot.getConnections().forEach(connection -> {
            System.out.println(connection.getOutgoingItem().getName() + " -> " + connection.getIncomingItem().getName() + " -> Value: " + connection.getValue() + " -> Color: " + connection.getFill());
        });
    }

**Comment by HanSolo** [comment]
I've made a little change with the latest commit, can you check if it now works for you?

**Comment by Pureandy** [comment]
The Change fixed the NPE but not the Problem that caused the NPE.

![CircularPlot](https://user-images.githubusercontent.com/6490663/95429804-2b626d00-094b-11eb-9159-467f753c30e6.png)

With the new Version I tried to Color every Connection Black with:
        
```
        circluarPlot.getConnections().forEach(connection -> {
        	connection.setFill(Color.BLACK);
        });
```

But for some Reason it cant find some of the connections, and they also dont have a Tooltip now because they got skipped because Connection was null.

**Comment by HanSolo** [comment]
Unfortunately I‘m a bit busy these days but I‘ll try to take a look at it asap.

**Comment by HanSolo** [comment]
Found some time to test it again and I hope I fixed it with commit: e77e632e430cdc5cc252c2d08f5b7fc6ce200e02
Could you give it a try? If it works for you I will release another version.

**Comment by Pureandy** [comment]
I can't find the commit, I just ran another test with the most recent Version and the Problem still exists.

**Comment by HanSolo** [comment]
Oh I might have forgotten to push it...can you please give it another try...?

**Comment by Pureandy** [comment]
Yes that fixed the Problem. Thank you very much.

**Comment by HanSolo** [comment]
Ah...very nice... :)

**Comment by Pureandy** [comment]
Could you make a new Release for the changes? :)

**Comment by HanSolo** [comment]
I'm doing that right now... :)
